config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants do
    resources :reviews, only: %i[new create index]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
  validates :phone_number, numericality: { only_integer: true }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { in: 0..5, only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = restaurant_finder
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(permit)
    @restaurant.save
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
  end

  def destroy
  end

  private

  def restaurant_finder
    @restaurant = Restaurant.find(params[:id])
  end

  def permit
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Reviews.all(params[:restaurant_id])
  end

  def new
    @restaurant = restaurant_finder
    @review = Review.new
  end

  def create
    @review = Review.new(permit)
    restaurant = restaurant_finder
    @review.restaurant = restaurant
    @review.save
    if @review.save
      redirect_to restaurant_path(restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def restaurant_finder
    Restaurant.find(params[:restaurant_id])
  end

  def permit
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :phone_number %>
  <%= f.submit %>
<% end %>

app/views/restaurants/_list.html.erb
<ul class="list-group">
  <% @restaurants.each do |restaurant| %>
    <li class="list-item">
      <%= link_to restaurant[:name], restaurant_path(restaurant) %>
    </li>
  <% end %>
</ul>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<%= render 'list', restaurant: @restaurants %>

<p>====================</p>

<%= link_to "Add new Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Add Restaurant</h1>

<%= render 'form', restaurant: @restaurants %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p> <%= @restaurant.category %> </p>
<p>====================</p>

<h4>Address: <%= @restaurant.address %></h4>
<h4>Number: <%= @restaurant.phone_number %></h4>

<p>====================</p>
<p><strong>Reviews</strong></p>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= "⭐️" * review.rating %></li>
    <li class="list-group-item"><%= review.content %>   <%= link_to '🗑️', review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
  <% end %>
</ul>
<%= link_to 'Add a review', new_restaurant_review_path(@restaurant) %>
<p>====================</p>

<%= link_to 'Back to List', restaurants_path %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a review</h1>
<%# <%= @restaurant[:name] %>
<div class="list-group">
  <%= render 'form', restaurant: @restaurant, review: @review %>
</div>